### ISSUE TITLE
Set up analytic dashboard plugin

### ISSUE THREAD

**Issue by RasonJ** [o19s/ubi-dashboards-ubi#5]

**Comment by RasonJ** [comment]
Starting building a demo dashboard that does real analytics.

**Comment by RasonJ** [comment]
Prolly not going through with this.

**Comment by epugh** [comment]
Yep..  we did the analysis and Stavros agreed that building out a giant plugin isn't the right approach for now.  For 2.13 and 2.14 at a minimum we document the heck out of this via katas plus plugin docs, and let users generate their own!   ---> We SHOULD attempt to make a kata where you "import" the dashboard for chorus.
